### ISSUE TITLE
Not generating all methods of a wrapped interface

### ISSUE THREAD

**Issue by tleyden** [ernesto-jimenez/goautomock#3]
If I run `go generate` against:

```
package mockcloudformation

import "github.com/aws/aws-sdk-go/service/cloudformation/cloudformationiface"

//go:generate goautomock -template=testify CloudFormationAPI

// Wrap the official cloudformationiface.CloudFormationAPI so we can use goautomock to generate mocks
// 
// Initially I tried running go:generate goautomock -template=testify cloudformationiface.CloudFormationAPI 
// but ran into errors, hence this workaround
// 
type CloudFormationAPI interface {

	cloudformationiface.CloudFormationAPI

}
```

it generates [cloud_formation_a_p_i_mock_test.go](https://gist.github.com/tleyden/963eb12038ab761c3635818731d13534), which is missing the `ListExports(*cloudformation.ListExportsInput) (*cloudformation.ListExportsOutput, error)` method, which is present in the [wrapped interface](https://github.com/aws/aws-sdk-go/blob/master/service/cloudformation/cloudformationiface/interface.go#L140).

Is there any way to avoid wrapping `cloudformationiface.CloudFormationAPI`?

Any alternative approaches for generating mocks for `cloudformationiface.CloudFormationAPI` would be welcome .. if this isn't the right approach.

**Comment by ernesto-jimenez** [comment]
@tleyden do you have the latest version of the `aws-sdk-go` package in your `GOPATH`?

Personally, I had the same issue because I had a previous release of the package installed locally. `ListExports` was added in last November.

Regarding how you are generating it, you can skip the wrapping interface and just do:

```
goautomock -pkg=github.com/aws/aws-sdk-go/service/cloudformation/cloudformationiface CloudFormationAPI
```

**Comment by tleyden** [comment]
Ok thanks!  That sounds like it will fix both of the issues I hit.

**Comment by tleyden** [comment]
> @tleyden do you have the latest version of the aws-sdk-go package in your GOPATH?

I updated the `aws-sdk-go` package in my `GOPATH` but still seeing the same issue .. but have a feeling maybe there is some old residue on my system somehow.  Will reopen if I can repro on a clean system.
