### ISSUE TITLE
Does not work with modules

### ISSUE THREAD

**Issue by mikegleasonjr** [ernesto-jimenez/goautomock#9]
Using Go modules outside of `$GOPATH` gives me: `can't find import: "."`

**Comment by mikegleasonjr** [comment]
Nevermind, you should archive this repo and redirect users to [mockery](https://github.com/vektra/mockery)

**Comment by soniah** [comment]
@ernesto-jimenez would it be possible to mark this repo as retired and refer people to other projects like `moq`, `mockery`, etc?
